version: '3.9'
services:
  birthday-tracker:
    build: .
    container_name: birthday-tracker
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: birthday-tracker-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
