version: '3.9'
services:
  birthday-tracker:
    build: .
    container_name: birthday-tracker
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@birthday-tracker-mongodb:27017
  mongodb:
    image: mongo
    container_name: birthday-tracker-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    command: mongod

volumes:
  mongodb:
